Repository theforeman/foreman_ansible, pull requests merged in 2018-02, with the labels that each got.

#128 Fixes #22539 - Sync ansible templates
  app/views/foreman_ansible/job_templates/ansible_roles_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/ansible_roles_-_install_from_galaxy.erb
  app/views/foreman_ansible/job_templates/ansible_roles_-_install_from_git.erb
  app/views/foreman_ansible/job_templates/power_action_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/puppet_run_once_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/run_command_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/service_action_-_ansible_default.erb
  script/sync_templates.sh
Labels: Needs testing, Not yet reviewed

#116 Fixes #22125 - Restore correct output for ansible reports
  app/helpers/foreman_ansible/ansible_reports_helper.rb
  app/services/foreman_ansible/ansible_report_scanner.rb
  app/views/foreman_ansible/config_reports/_output.html.erb
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
  test/fixtures/report.json
  test/test_plugin_helper.rb
  test/unit/concerns/config_reports_extensions_test.rb
  test/unit/helpers/foreman_ansible/ansible_reports_helper_test.rb
Labels: Needs testing

#118 Fixes #22126 - Always show 'Play Roles' button for Hostgroups
  app/models/concerns/foreman_ansible/has_many_ansible_roles.rb
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  app/views/foreman_ansible/ansible_roles/_hostgroup_ansible_roles_button.erb
Labels: Needs testing

#132 Fixes #22625 - ignore facts in report page
  app/helpers/foreman_ansible/ansible_reports_helper.rb
Labels: Needs testing

#119 Fixes #22378 - Insights remediation playbook macro
  app/services/foreman_ansible/insights_plan_runner.rb
  app/services/foreman_ansible/renderer_methods.rb
  app/views/foreman_ansible/job_templates/maintenance_plan.erb
  lib/foreman_ansible/register.rb
  lib/foreman_ansible/remote_execution.rb
Labels: Needs testing, Not yet reviewed

#136 Fixes #22643 - Config strings may not be displayed
  app/helpers/foreman_ansible/ansible_reports_helper.rb
  test/unit/helpers/ansible_reports_helper_test.rb
Labels: Needs testing, Not yet reviewed

#135 Fixes #22634 - Reuse remote execution settings
  app/models/foreman_ansible/ansible_provider.rb
  app/models/setting/ansible.rb
  app/services/foreman_ansible/inventory_creator.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs re-review, Needs testing
