Repository theforeman/foreman_ansible, pull requests merged in 2018-04, with the labels that each got.

#157 Fixes #23091 - remove dynflow dep
  foreman_ansible.gemspec
Labels: Needs testing

#147 Fixes #22896 - Fall back to REX private key
  app/services/foreman_ansible/inventory_creator.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing

#158 Fixes #23114 - Add setting to disable out of sync
  app/models/setting/ansible.rb
Labels: Needs testing

#159 Fixes #23205 - Prefix job template categories with "Ansible"
  app/views/foreman_ansible/job_templates/package_action_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/power_action_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/puppet_run_once_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/run_command_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/service_action_-_ansible_default.erb
  db/migrate/20180410125416_rename_ansible_job_categories.rb
Labels: Needs testing, Waiting on contributor

#160 Fixes #23216 - Include package.json and webpack in gemspec
  foreman_ansible.gemspec
Labels: Needs testing, Not yet reviewed

#165 Fixes #23245 - Rubocop issues in master
  app/controllers/foreman_ansible/api/v2/hostgroups_controller_extensions.rb
  app/controllers/foreman_ansible/api/v2/hosts_controller_extensions.rb
  app/models/setting/ansible.rb
  app/services/foreman_ansible/ui_roles_importer.rb
  db/migrate/20180410125416_rename_ansible_job_categories.rb
  db/seeds.d/75_job_templates.rb
  lib/foreman_ansible/engine.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing, Not yet reviewed

#155 Fixes #23049 - Add IDs to the server respones
  app/views/api/v2/ansible_roles/show.json.rabl
Labels: Needs testing

#151 Fixes #22994 - Add refactor for ansible roles controller
  app/controllers/api/v2/ansible_roles_controller.rb
Labels: Needs testing

#167 Refs #23205 - fix the migration on existing setups
  db/migrate/20180410125416_rename_ansible_job_categories.rb
Labels: Needs testing

#164 Fixes #23243 - Display disclaimer on Insights playbook
  app/services/foreman_ansible/insights_plan_runner.rb
  app/services/foreman_ansible/renderer_methods.rb
  test/fixtures/insights_playbook.yaml
  test/unit/services/insights_plan_runner_test.rb
Labels: Needs testing
