Repository theforeman/foreman_ansible, pull requests merged in 2018-07, with the labels that each got.

#180 Fixes #23879 - Disable Ansible Callback when running commands
  app/models/foreman_ansible/ansible_provider.rb
  lib/foreman_ansible_core/command_creator.rb
  test/unit/ansible_provider_test.rb
  test/unit/lib/foreman_ansible_core/command_creator_test.rb
Labels: Needs testing

#183 Fixes #24163 - Power Action does not do anything
  app/views/foreman_ansible/job_templates/power_action_-_ansible_default.erb
Labels: Ready to merge

#184 Fixes #23279 - Enable 'ansible_become' to work with REX
  app/models/foreman_ansible/ansible_provider.rb
  app/services/foreman_ansible/inventory_creator.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing, Not yet reviewed

#185 Fixes #24207 - don't display run buttons for unauthorized users
  app/helpers/foreman_ansible/hosts_helper_extensions.rb
  app/views/foreman_ansible/ansible_roles/_hostgroup_ansible_roles_button.erb
Labels: Needs testing

#188 Fixes #24244 - add ipaddress dependency
  foreman_ansible.gemspec
Labels: Needs testing

#182 Fixes #24038 - don't display host roles in hg form
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  app/views/foreman_ansible/ansible_roles/_select_tab_content.html.erb
Labels: Needs testing

#189 Refs #24163 - shutdown with 1m delay so callback can return
  app/views/foreman_ansible/job_templates/power_action_-_ansible_default.erb
Labels: Ready to merge

#190 Fixes #24296 - Remove option to import roles from Foreman host
  app/helpers/foreman_ansible/ansible_roles_helper.rb
Labels: Ready to merge

#192 Fixes #24361 - import_host arguments in foreman-core changed
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
Labels: Needs testing

#191 Fixes #24038 - fix host roles inheritance from hostgroup
  app/models/concerns/foreman_ansible/has_many_ansible_roles.rb
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  test/unit/concerns/host_managed_extensions_test.rb
  test/unit/concerns/hostgroup_extensions_test.rb
Labels: Needs testing

#194 Unpin net-ssh dependency
  foreman_ansible_core.gemspec
Labels: Needs testing, Waiting on contributor

#186 Fix Performance/HashEachMethods cop
  app/services/foreman_ansible/ui_roles_importer.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
