Repository theforeman/foreman_ansible, pull requests merged in 2018-03, with the labels that each got.

#141 Fixes #19149 - Check whether gem is loaded on SCL or not
  lib/foreman_ansible_core.rb
Labels: Needs testing, Not yet reviewed

#142 Fixes #22774 - ssh_private_key_path setting does not show up
  app/models/setting/ansible.rb
Labels: Needs testing, Not yet reviewed

#137 Refs #22125 - Use react-json-tree for report json rendering
  .bablerc
  .eslintignore
  .eslintrc
  .gitignore
  app/assets/stylesheets/foreman_ansible/foreman-ansible.css
  app/helpers/foreman_ansible/ansible_reports_helper.rb
  app/views/foreman_ansible/config_reports/_ansible.html.erb
  lib/foreman_ansible/engine.rb
  package.json
  test/unit/helpers/ansible_reports_helper_test.rb
  webpack/components/ReportJsonViewer.js
  webpack/index.js
Labels: Needs testing

#123 Fixes #22124 - Add report interval setting for Ansible
  app/models/setting/ansible.rb
  lib/foreman_ansible/register.rb
Labels: Needs testing

#149 Fixes rubocop
  app/models/setting/ansible.rb
  db/seeds.d/75_job_templates.rb
Labels: Needs testing, Waiting on contributor

#148 Remove tasks version limit
  foreman_ansible.gemspec
Labels: Needs testing, Waiting on contributor

#143 Fixes #22775 - add missing audits for user actions
  app/models/ansible_role.rb
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  app/models/host_ansible_role.rb
Labels: Needs testing

#146 Fixes #22860 - Extract the most recent strings from the ansible plugin
  locale/en/foreman_ansible.po
  locale/foreman_ansible.pot
Labels: Needs re-review, Needs testing

#150 Fixes #22973 - add custom insights notification
  .rubocop_todo.yml
  app/services/foreman_ansible/insights_notification_builder.rb
  db/seeds.d/90_notification_blueprints.rb
  lib/foreman_ansible/remote_execution.rb
Labels: Needs testing
