Repository theforeman/foreman_ansible, pull requests merged in 2018-06, with the labels that each got.

#177 Fixes #23742 - share all templates to all taxonomies
  db/seeds.d/75_job_templates.rb
Labels: Needs testing

#153 Fixes #23047 - PUT instead of POST for import/obsolete API endpoints
  app/controllers/api/v2/ansible_roles_controller.rb
  test/functional/api/v2/ansible_roles_controller_test.rb
Labels: Needs testing, Not yet reviewed

#174 Fixes #23715 - Verify OS facts before submitting them
  app/services/foreman_ansible/fact_parser.rb
  app/services/foreman_ansible/operating_system_parser.rb
  test/unit/services/fact_parser_test.rb
Labels: Ready to merge

#176 Fixes #23731 - Add host key to known_hosts if not found
  foreman_ansible_core.gemspec
  lib/foreman_ansible_core/playbook_runner.rb
  test/unit/lib/foreman_ansible_core/playbook_runner_test.rb
Labels: Needs testing, Waiting on contributor

#179 Fixes #23545 - Move post-provisioning Ansible to REX
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/services/foreman_ansible/proxy_selector.rb
  test/unit/services/proxy_selector_test.rb
Labels: Needs testing

#181 Fixes #24061 - Make tests ansible_dir use Dir.home
  test/unit/lib/foreman_ansible_core/playbook_runner_test.rb
Labels: Needs testing, Not yet reviewed
