Repository theforeman/foreman_ansible, pull requests merged in 2019-02, with the labels that each got.

#239 Make deb OS facts parsing more reliable
  .rubocop.yml
  app/controllers/api/v2/ansible_override_values_controller.rb
  app/services/foreman_ansible/operating_system_parser.rb
  test/unit/services/fact_parser_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#242 Fixes #25989 - move play roles button
  app/helpers/foreman_ansible/hosts_helper_extensions.rb
  lib/foreman_ansible/remote_execution.rb
Labels: Needs testing, Not yet reviewed

#244 Fixes #26064 - add missing search route
  config/routes.rb
Labels: Waiting on contributor

#245 Fix rubocop offenses
  app/services/foreman_ansible/inventory_creator.rb
  config/routes.rb
  db/seeds.d/90_notification_blueprints.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#247 Fixes #26101 - Add missing permissions
  lib/foreman_ansible/register.rb
Labels: Ready to merge

#246 Fixes #26093 - restore searching by role
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/views/ansible_roles/index.html.erb
Labels: Ready to merge

#225 Fixes #26161 - Assigning Ansible roles over the API
  app/controllers/foreman_ansible/api/v2/hostgroups_controller_extensions.rb
  app/controllers/foreman_ansible/api/v2/hosts_controller_extensions.rb
  app/controllers/foreman_ansible/concerns/api_common.rb
  config/routes.rb
  lib/foreman_ansible/register.rb
  test/functional/api/v2/hostgroups_controller_test.rb
  test/functional/api/v2/hosts_controller_test.rb
Labels: Waiting on contributor

#248 Refs #25977 - unify override tooltip with smart variables
  app/views/ansible_variables/index.html.erb
Labels: Needs testing, Not yet reviewed
