Repository theforeman/foreman_ansible, pull requests merged in 2019-01, with the labels that each got.

#234 Update versions in readme
  README.md
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#226 Fixes #25531 - Fetch endpoint uses proxy
  app/controllers/api/v2/ansible_roles_controller.rb
  app/services/foreman_ansible/roles_importer.rb
  test/functional/api/v2/ansible_roles_controller_test.rb
Labels: Needs testing, Not yet reviewed

#229 Fixes #25741 - remove leftover requirement
  lib/foreman_ansible/engine.rb
Labels: Needs testing

#236 Disabling metrics cops as in core
  .rubocop.yml
  .rubocop_todo.yml
Labels: Needs testing, Waiting on contributor

#233 Fixes #25779 - complete variables API
  app/controllers/api/v2/ansible_override_values_controller.rb
  app/controllers/api/v2/ansible_variables_controller.rb
  app/controllers/concerns/foreman/controller/parameters/ansible_override_value.rb
  app/views/api/v2/ansible_override_values/show.json.rabl
  app/views/api/v2/ansible_variables/destroy.json.rabl
  app/views/api/v2/ansible_variables/show.json.rabl
  config/routes.rb
Labels: Needs testing, Not yet reviewed

#237 Fixes #25455 - Add variables into host_params
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  lib/foreman_ansible/engine.rb
Labels: Needs testing

#238 Fix fact parser test
  app/services/foreman_ansible/operating_system_parser.rb
  test/unit/services/fact_parser_test.rb
Labels: Needs testing, Waiting on contributor
