Repository theforeman/foreman_ansible, pull requests merged in 2019-07, with the labels that each got.

#281 Fixes #27270 - Remove ansible roles from hostgroup
  webpack/components/AnsibleRolesSwitcher/components/AssignedRolesList.js
Labels: Needs testing

#282 Fixes #27311 - Assume job is successful for a host unless indicated
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing, Not yet reviewed

#285 Fixes #27329 - Fix host params key
  app/views/foreman_ansible/job_templates/ansible_roles_-_ansible_default.erb
Labels: Needs testing

#287 Fix obsolete cop names
  .rubocop_todo.yml
  app/controllers/api/v2/ansible_inventories_controller.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#290 Fixes #27381 - setting description fix
  app/models/setting/ansible.rb
Labels: Needs testing

#286 Fixes #27361 - Add generated translations
  .gitignore
  locale/de/LC_MESSAGES/foreman_ansible.mo
  locale/en/LC_MESSAGES/foreman_ansible.mo
  locale/es/LC_MESSAGES/foreman_ansible.mo
  locale/fr/LC_MESSAGES/foreman_ansible.mo
  locale/it/LC_MESSAGES/foreman_ansible.mo
  locale/ja/LC_MESSAGES/foreman_ansible.mo
  locale/ko/LC_MESSAGES/foreman_ansible.mo
  locale/pt_BR/LC_MESSAGES/foreman_ansible.mo
  locale/ru/LC_MESSAGES/foreman_ansible.mo
  locale/zh_CN/LC_MESSAGES/foreman_ansible.mo
  locale/zh_TW/LC_MESSAGES/foreman_ansible.mo
Labels: Needs testing, Not yet reviewed

#294 Fixes #27021 - make runner default implementation
  app/models/setting/ansible.rb
Labels: Needs testing
