Repository theforeman/foreman_ansible, pull requests merged in 2019-10, with the labels that each got.

#249 Fixes #26202 - Uses hardware MAC-address whenever possible
  app/services/foreman_ansible/fact_parser.rb
  test/unit/services/fact_parser_test.rb
Labels: Needs re-review, Needs testing

#303 Refs #27746 - use newer rex version
  foreman_ansible.gemspec
Labels: Needs testing, Waiting on contributor

#305 Refs #26202 - fix rubocop
  test/unit/services/fact_parser_test.rb
Labels: Needs testing, Not yet reviewed

#302 Fixes #27984 - Provide an option to run a job with playbook as input
  app/views/foreman_ansible/job_templates/run_playbook-ansible_default.erb
  lib/foreman_ansible/remote_execution.rb
Labels: Needs testing

#306 Fixes #28042 - remove ansible-playbook option
  app/models/foreman_ansible/ansible_provider.rb
  app/models/setting/ansible.rb
  db/migrate/20191010074208_remove_ansible_implementation_setting.rb
Labels: Needs testing, Not yet reviewed

#299 Fixes #27937 - API for Ansible Inventory template scheduling
  app/controllers/api/v2/ansible_inventories_controller.rb
  app/models/setting/ansible.rb
  config/routes.rb
  lib/foreman_ansible/register.rb
Labels: 4.0, Needs testing

#300 Fixes #27816 - setting initialization improvement
  app/models/setting/ansible.rb
Labels: 4.0, Needs testing

#279 Fixes #28073 - parse boot time fact
  Rakefile
  app/services/foreman_ansible/fact_parser.rb
  config/routes.rb
Labels: 4.0, Needs testing

#288 Fixes #27388 - migrate to @theforeman/vendor pkg
  .babelrc
  .eslintrc
  package.json
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.scss
Labels: 3.0, 4.0, Needs re-review, Needs testing, Waiting on contributor

#309 Fixes #28113 - Replace deprecated db_facts method
  app/services/foreman_ansible/fact_importer.rb
  test/unit/services/fact_importer_test.rb
Labels: 4.0, Needs testing

#308 Refs #27388 - Update @theforeman/vendor for 1.24
  package.json
Labels: Needs testing
