Repository theforeman/foreman_ansible, pull requests merged in 2019-09, with the labels that each got.

#297 Fixes #27663 - Make ansible var keys unique
  app/models/ansible_variable.rb
Labels: Ready to merge

#298 Fixes #27747 - Remove taxonomy enabled checks
  db/seeds.d/75_job_templates.rb
Labels: Needs testing

#291 Fixes #27435 - icon_path instead origin to override
  app/models/foreman_ansible/fact_name.rb
Labels: Ready to merge

#293 Fixes #27445 - Properly serialize default var values
  app/models/ansible_variable.rb
  test/unit/ansible_variable_test.rb
Labels: Needs testing, Ready to merge

#289 Fixes #27389 - fix eslint
  .eslintrc
  package.json
  webpack/__mocks__/foremanReact/common/I18n.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.js
  webpack/components/AnsibleRolesSwitcher/components/AnsiblePermissionDenied.js
  webpack/components/AnsibleRolesSwitcher/components/AnsibleRole.js
  webpack/components/AnsibleRolesSwitcher/components/AssignedRolesList.js
  webpack/index.js
Labels: Needs testing

#301 Fixes #27834 - Expect runner json may miss event_data key
  lib/foreman_ansible_core/runner/ansible_runner.rb
  test/unit/lib/foreman_ansible_core/ansible_runner_test.rb
Labels: Needs testing

#295 Fixes #27491 - Ensure ssh and sudo password are not leaked
  app/models/foreman_ansible/ansible_provider.rb
  app/services/foreman_ansible/inventory_creator.rb
  lib/foreman_ansible_core/runner/ansible_runner.rb
  lib/foreman_ansible_core/runner/playbook.rb
  test/unit/ansible_provider_test.rb
  test/unit/lib/foreman_ansible_core/ansible_runner_test.rb
  test/unit/lib/foreman_ansible_core/playbook_runner_test.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing
