Repository theforeman/foreman_ansible, pull requests merged in 2019-04, with the labels that each got.

#240 Add support for using ansible-runner
  app/models/foreman_ansible/ansible_provider.rb
  app/models/setting/ansible.rb
  foreman_ansible_core.gemspec
  lib/foreman_ansible_core.rb
  lib/foreman_ansible_core/actions.rb
  lib/foreman_ansible_core/playbook_runner.rb
  lib/foreman_ansible_core/remote_execution_core/ansible_runner.rb
  lib/foreman_ansible_core/remote_execution_core/settings_override.rb
  lib/foreman_ansible_core/runner/ansible_runner.rb
  lib/foreman_ansible_core/runner/command_creator.rb
  lib/foreman_ansible_core/runner/playbook.rb
  lib/foreman_ansible_core/task_launcher/ansible_runner.rb
  lib/foreman_ansible_core/task_launcher/playbook.rb
  test/unit/lib/foreman_ansible_core/playbook_runner_test.rb
Labels: Needs testing, Waiting on contributor

#258 Fixes #26068 - Improve inventory structure
  app/models/setting/ansible.rb
  app/services/foreman_ansible/inventory_creator.rb
  db/migrate/20190328114657_remove_top_level_ansible_variables_setting.rb
  test/factories/ansible_variables.rb
  test/unit/services/inventory_creator_test.rb
Labels: 3.0, Needs re-review, Needs testing

#259 Fixes #25361 - Disable ansible_become_user on connect
  app/services/foreman_ansible/inventory_creator.rb
Labels: Needs testing

#263 Fixes #26670 - Change node packages to be compatible with develop
  package.json
Labels: Needs testing

#260 Fixes #25722 - Redirect to index when no changes in vars
  app/controllers/ansible_variables_controller.rb
  test/functional/ansible_variables_controller_test.rb
Labels: Needs testing

#266 Fixes #26706 - use foreman_ansible_core 3
  foreman_ansible.gemspec
Labels: Needs testing
