Repository theforeman/foreman_ansible, pull requests merged in 2019-03, with the labels that each got.

#251 Fixes #26272 - Use cdn_proxy to fetch playbook from Red Hat Insights
  app/services/foreman_ansible/insights_plan_runner.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#217 Fixes #25309 - Switcher for ansible roles
  .babelrc
  .eslintrc
  .travis.yml
  app/controllers/ui_ansible_roles_controller.rb
  app/helpers/foreman_ansible/ansible_roles_helper.rb
  app/models/ansible_role.rb
  app/views/foreman_ansible/ansible_roles/_select_tab_content.html.erb
  app/views/ui_ansible_roles/index.json.rabl
  app/views/ui_ansible_roles/main.json.rabl
  app/views/ui_ansible_roles/show.json.rabl
  config/routes.rb
  lib/foreman_ansible/register.rb
  package.json
  script/travis_run_js_tests.sh
  test/functional/ui_ansible_roles_controller_test.rb
  webpack/__mocks__/foremanReact/components/Pagination/PaginationWrapper.js
  webpack/__mocks__/foremanReact/components/common/EmptyState.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.scss
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcherActions.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcherConstants.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcherHelpers.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcherReducer.js
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcherSelectors.js
  webpack/components/AnsibleRolesSwitcher/__fixtures__/ansibleRolesData.fixtures.js
  webpack/components/AnsibleRolesSwitcher/__fixtures__/ansibleRolesSwitcherReducer.fixtures.js
  webpack/components/AnsibleRolesSwitcher/__tests__/AnsibleRolesSwitcher.test.js
  webpack/components/AnsibleRolesSwitcher/__tests__/AnsibleRolesSwitcherReducer.test.js
  webpack/components/AnsibleRolesSwitcher/__tests__/AnsibleRolesSwitcherSelectors.test.js
  webpack/components/AnsibleRolesSwitcher/__tests__/__snapshots__/AnsibleRolesSwitcher.test.js.snap
  webpack/components/AnsibleRolesSwitcher/__tests__/__snapshots__/AnsibleRolesSwitcherReducer.test.js.snap
  webpack/components/AnsibleRolesSwitcher/__tests__/__snapshots__/AnsibleRolesSwitcherSelectors.test.js.snap
  webpack/components/AnsibleRolesSwitcher/components/AnsiblePermissionDenied.js
  webpack/components/AnsibleRolesSwitcher/components/AnsiblePermissionDenied.test.js
  webpack/components/AnsibleRolesSwitcher/components/AnsibleRole.js
  webpack/components/AnsibleRolesSwitcher/components/AnsibleRole.test.js
  webpack/components/AnsibleRolesSwitcher/components/AnsibleRoleActionButton.js
  webpack/components/AnsibleRolesSwitcher/components/AnsibleRolesSwitcherError.js
  webpack/components/AnsibleRolesSwitcher/components/AssignedRolesList.js
  webpack/components/AnsibleRolesSwitcher/components/AssignedRolesList.test.js
  webpack/components/AnsibleRolesSwitcher/components/AvailableRolesList.js
  webpack/components/AnsibleRolesSwitcher/components/AvailableRolesList.test.js
  webpack/components/AnsibleRolesSwitcher/components/__snapshots__/AnsiblePermissionDenied.test.js.snap
  webpack/components/AnsibleRolesSwitcher/components/__snapshots__/AnsibleRole.test.js.snap
  webpack/components/AnsibleRolesSwitcher/components/__snapshots__/AssignedRolesList.test.js.snap
  webpack/components/AnsibleRolesSwitcher/components/__snapshots__/AvailableRolesList.test.js.snap
  webpack/components/AnsibleRolesSwitcher/components/withProtectedView.js
  webpack/components/AnsibleRolesSwitcher/index.js
  webpack/components/ReportJsonViewer.js
  webpack/index.js
  webpack/reducer.js
  webpack/test_setup.js
Labels: Needs testing

#253 Fixes #26335 - documentation link in new tab
  app/views/ansible_roles/welcome.html.erb
Labels: Needs testing, Not yet reviewed

#255 Fixes #26431 - ship inventory role by default
  lib/foreman_ansible/register.rb
Labels: Needs re-review, Needs testing

#257 Cherry-picks for 2.2.14
  config/routes.rb
  lib/foreman_ansible/register.rb
Labels: Needs testing, Not yet reviewed

#256 Fixes #26436 - restore compatibility with 1.21
  app/views/ansible_variables/_fields.erb
  lib/foreman_ansible/register.rb
Labels: Needs testing, Not yet reviewed

#252 Fixes #26264, #25721 - Detect variable types on import
  app/controllers/ansible_variables_controller.rb
  app/services/foreman_ansible/variables_importer.rb
  app/views/ansible_variables/import.html.erb
  test/unit/services/ansible_variables_importer_test.rb
Labels: Needs testing

#254 Fixes #26391 - Allow custom Ansible variables
  .rubocop.yml
  .rubocop_todo.yml
  app/assets/stylesheets/foreman_ansible/foreman-ansible.css
  app/controllers/ansible_variables_controller.rb
  app/controllers/api/v2/ansible_variables_controller.rb
  app/controllers/concerns/foreman/controller/parameters/ansible_variable.rb
  app/helpers/foreman_ansible/ansible_roles_helper.rb
  app/models/ansible_variable.rb
  app/services/foreman_ansible/variables_importer.rb
  app/views/ansible_variables/_fields.erb
  app/views/ansible_variables/index.html.erb
  app/views/ansible_variables/new.html.erb
  app/views/api/v2/ansible_variables/create.json.rabl
  app/views/api/v2/ansible_variables/show.json.rabl
  config/routes.rb
  db/migrate/20190318094437_add_imported_attr_to_ansible_variables.rb
  lib/foreman_ansible/register.rb
  test/factories/ansible_variables.rb
  test/functional/ansible_variables_controller_test.rb
  test/functional/api/v2/ansible_variables_controller_test.rb
  test/unit/services/ansible_variables_importer_test.rb
Labels: Needs testing
