Repository theforeman/foreman_ansible, pull requests merged in 2019-12, with the labels that each got.

#315 Fixes #28431 - Fix double encoded JSON issue
  app/models/foreman_ansible/ansible_provider.rb
Labels: Needs testing

#317 Fix rubocop
  app/services/foreman_ansible/variables_importer.rb
  lib/foreman_ansible/engine.rb
  test/functional/hosts_controller_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#316 Fixes #28447 - fix the permission definition
  lib/foreman_ansible/register.rb
  test/functional/api/v2/ansible_inventories_controller_test.rb
Labels: Needs re-review, Needs testing

#318 Fixes #28463 - Fix missing roles in the assigned roles list
  webpack/components/AnsibleRolesSwitcher/AnsibleRolesSwitcher.js
  webpack/components/AnsibleRolesSwitcher/components/AssignedRolesList.js
  webpack/components/AnsibleRolesSwitcher/components/AssignedRolesList.test.js
Labels: Needs re-review, Needs testing

#319 Fix eslint offence
  webpack/components/AnsibleRolesSwitcher/index.js
Labels: Needs testing, Waiting on contributor

#320 Fix Rubocop
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/api/v2/ansible_roles_controller.rb
  app/controllers/foreman_ansible/api/v2/hostgroups_controller_extensions.rb
  app/controllers/foreman_ansible/api/v2/hosts_controller_extensions.rb
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/models/setting/ansible.rb
  app/services/foreman_ansible/insights_notification_builder.rb
  app/services/foreman_ansible/operating_system_parser.rb
  config/routes.rb
  db/migrate/20160802153302_create_join_table_hostgroup_ansible_roles.rb
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
  test/functional/api/v2/ansible_inventories_controller_test.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing, Waiting on contributor
