Repository theforeman/foreman_ansible, pull requests merged in 2020-01, with the labels that each got.

#322 Check to see if variables is nil before proceeding
  app/services/foreman_ansible/variables_importer.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#324 Fixes #28662 - Remove VariableLookupKey reference
  app/controllers/api/v2/ansible_variables_controller.rb
  test/functional/api/v2/ansible_variables_controller_test.rb
Labels: Needs testing

#321 Drop tasks dependency
  foreman_ansible.gemspec
Labels: Needs testing, Waiting on contributor

#311 Fixes #28253 - upgrade vendor to v3
  .babelrc
  .babelrc.js
  package.json
  webpack/test_setup.js
Labels: Needs testing
