Repository theforeman/foreman_ansible, pull requests merged in 2020-02, with the labels that each got.

#325 Fixes #28937 - ansible variable type form field
  app/views/ansible_variables/_fields.erb
Labels: Needs testing, Not yet reviewed

#326 fixes #28963: Do not evaluate shell characters while returning the inventory
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing, Waiting on contributor

#329 Fixes #29064 - Remove Enable_Smart_Variables_in_ENC from test
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing

#327 Fixes #29034 - Update Ansible API docs for inventories
  app/controllers/api/v2/ansible_inventories_controller.rb
  config/routes.rb
Labels: Needs re-review, Needs testing

#330 Fixes #29138 - Fix rendering overriden False variables in YAML output
  app/services/foreman_ansible/ansible_info.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
