Repository theforeman/foreman_ansible, pull requests merged in 2020-08, with the labels that each got.

#261 Fixes #22804 - Parse origin for failed runs
  app/services/foreman_ansible/ansible_report_importer.rb
  app/services/foreman_ansible/ansible_report_scanner.rb
  test/fixtures/report.json
  webpack/components/ReportJsonViewer.js
Labels: Needs testing

#356 [Rubocop] Allow both Hash styles
  .rubocop.yml
Labels: Needs testing

#353 Fixes #30483 - Give Foreman operation jobs their own Job Category
  app/views/foreman_ansible/job_templates/capsule_upgrade_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/configure_cloud_connector_-_ansible_default.erb
Labels: Needs re-review, Needs testing

#355 Fixes #30545 - Pass whitelist options only if provided by the user
  app/views/foreman_ansible/job_templates/capsule_upgrade_-_ansible_default.erb
Labels: Needs testing, Waiting on contributor

#360 Refs #30384 - Fix broken ansible provider test
  test/unit/ansible_provider_test.rb
Labels: Needs testing

#323 Fixes #28612 - Fix runs when proxy batch triggering is disabled
  app/models/foreman_ansible/ansible_provider.rb
Labels: Needs testing

#354 Fixes #30518 - Remove working directory
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing

#357 Allow GH actions and drop travis
  .codeclimate.yml
  .github/workflows/js_tests.yml
  .github/workflows/ruby_tests.yml
  .rubocop.yml
  .rubocop_todo.yml
  .travis.yml
  Gemfile
  foreman_ansible.gemspec
  foreman_ansible_core.gemspec
  script/travis_run_js_tests.sh
Labels: Needs testing, Waiting on contributor
