Repository theforeman/foreman_ansible, pull requests merged in 2020-04, with the labels that each got.

#340 Sync templates
  app/views/foreman_ansible/job_templates/configure_cloud_connector_-_ansible_default.erb
Labels: Needs testing, Waiting on contributor

#332 Fixes #29293 - Update Rubocop to 0.80
  .rubocop.yml
  .rubocop_todo.yml
  app/services/foreman_ansible/operating_system_parser.rb
  foreman_ansible.gemspec
  foreman_ansible_core.gemspec
  lib/foreman_ansible/engine.rb
Labels: Needs testing

#335 Fixes #28859, #26485 - ansible import variables uniquely per role
  app/services/foreman_ansible/variables_importer.rb
  test/factories/ansible_variables.rb
  test/unit/services/ansible_variables_importer_test.rb
Labels: Needs re-review, Needs testing

#341 Fixes #29528 - rubocop task definition
  lib/tasks/foreman_ansible_tasks.rake
Labels: Needs testing, Not yet reviewed

#342 Fixes #29587 - Update default template name for Ansible inventory
  app/models/setting/ansible.rb
  db/migrate/20200421201839_update_ansible_inv_template_name.rb
Labels: Needs testing, Not yet reviewed

#343 Fixes #29627 - fixed ansible-runner verbosity in plays
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing
