Repository theforeman/foreman_ansible, pull requests merged in 2021-08, with the labels that each got.

#437 Refs #33142 - add missing permissions
  lib/foreman_ansible/register.rb
Labels: Needs testing, Not yet reviewed

#436 Fixes #33152 - Do not use translated stings as hash keys
  app/helpers/foreman_ansible/ansible_roles_data_preparations.rb
Labels: Needs testing

#434 Fixes #25579 - allow Ansible Manager to run jobs
  lib/foreman_ansible/register.rb
Labels: Needs re-review, Needs testing

#440 Fixes #25579 - allow Ansible Manager to run jobs
  lib/foreman_ansible/register.rb
Labels: Needs testing, Not yet reviewed

#439 Fixes #33152 - Do not use translated stings as hash keys
  app/helpers/foreman_ansible/ansible_roles_data_preparations.rb
Labels: Needs testing

#442 Fixes #31101 - copy ansible roles when cloning a hostgroup
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  test/unit/concerns/hostgroup_extensions_test.rb
Labels: Needs testing

#432 Fixes #33139 - Show Ansible roles on Host detail page
  lib/foreman_ansible/register.rb
  test/graphql/queries/ansible_roles_query_test.rb
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTab.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/index.js
  webpack/components/AnsibleHostDetail/components/TabLayout.js
  webpack/components/withLoading.js
  webpack/graphql/queries/ansibleRoles.gql
Labels: Needs testing

#447 Fixes #30833 - Add search by role to hosts
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  test/unit/concerns/host_managed_extensions_test.rb
Labels: Needs testing, Not yet reviewed

#443 Refs #24367 - Support setting key passphrase through settings
  app/models/foreman_ansible/ansible_provider.rb
Labels: Needs testing, Not yet reviewed

#449 Fixes #33284 - Do not override host_setting method
  app/models/foreman_ansible/ansible_provider.rb
  test/unit/ansible_provider_test.rb
Labels: Needs testing, Not yet reviewed

#450 Fixes #33284 - Do not override host_setting method
  app/models/foreman_ansible/ansible_provider.rb
  test/unit/ansible_provider_test.rb
Labels: Needs testing, Not yet reviewed

#453 Fixes #33218 - Only ansible config jobs now run in check mode
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing, Not yet reviewed
