Repository theforeman/foreman_ansible, pull requests merged in 2021-02, with the labels that each got.

#381 Fix #31709 - prefer lsb facts for OS
  app/services/foreman_ansible/operating_system_parser.rb
Labels: Needs testing, Not yet reviewed

#369 Write cache on push to master
  .github/workflows/ruby_tests.yml
Labels: Needs testing, Waiting on contributor

#313 Fixes #28344 - Add endpoint for variable overrides
  app/controllers/ansible_variables_controller.rb
  app/controllers/foreman_ansible/concerns/ansible_variable_overrides.rb
  app/controllers/ui_ansible_roles_controller.rb
  app/services/foreman_ansible/override_resolver.rb
  config/routes.rb
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
  test/unit/services/override_resolver_test.rb
Labels: Needs testing

#380 Fixes #27273 - Specify order for ansible roles
  app/helpers/foreman_ansible/ansible_roles_helper.rb
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  app/models/host_ansible_role.rb
  app/models/hostgroup_ansible_role.rb
  app/views/foreman_ansible/ansible_roles/_select_tab_content.html.erb
  db/migrate/20210120150019_add_position_to_ansible_role.rb
  foreman_ansible.gemspec
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
  test/factories/ansible_roles.rb
  test/functional/api/v2/hostgroups_controller_test.rb
  test/functional/api/v2/hosts_controller_test.rb
  test/functional/hosts_controller_test.rb
  test/unit/concerns/host_managed_extensions_test.rb
  test/unit/concerns/hostgroup_extensions_test.rb
  test/unit/host_ansible_role_test.rb
  test/unit/hostgroup_ansible_role_test.rb
  test/unit/services/inventory_creator_test.rb
Labels: Needs testing
