Repository theforeman/foreman_ansible, pull requests merged in 2021-01, with the labels that each got.

#373 Fixes #31488, #23288 - Galaxy install location
  app/views/foreman_ansible/job_templates/ansible_roles_-_install_from_galaxy.erb
Labels: Needs testing

#377 Fix running js tests
  .github/workflows/js_tests.yml
Labels: Needs testing, Waiting on contributor

#378 Fixes #31651 - show the value of imported values
  app/services/foreman_ansible/variables_importer.rb
  test/unit/services/ansible_variables_importer_test.rb
Labels: Needs re-review, Needs testing
