Repository theforeman/foreman_ansible, pull requests merged in 2021-04, with the labels that each got.

#399 Fixes #32148 - Add ansible check mode global parameter
  db/seeds.d/100_common_parameters.rb
Labels: Ready to merge

#396 Fixes #31991 - API for importing roles & variables
  app/controllers/api/v2/ansible_roles_controller.rb
  app/controllers/api/v2/ansible_variables_controller.rb
  app/helpers/foreman_ansible/ansible_roles_data_preparations.rb
  app/services/foreman_ansible/api_roles_importer.rb
  app/views/api/v2/ansible_roles/sync.json.rabl
  config/routes.rb
  lib/foreman_ansible/register.rb
  test/functional/api/v2/ansible_roles_controller_test.rb
  test/unit/services/api_roles_importer_test.rb
Labels: Needs re-review, Needs testing

#400 Fixes #30090 - fix the controller permission mapping
  app/controllers/ansible_variables_controller.rb
Labels: Needs testing
