Repository theforeman/foreman_ansible, pull requests merged in 2021-09, with the labels that each got.

#452 Fixes #33313 - Consider jobs on unreachable hosts failed
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing, Not yet reviewed

#454 Fixes #33339 - add routable tabs in host details
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
  webpack/components/AnsibleHostDetail/components/SecondaryTabRoutes.js
  webpack/components/AnsibleHostDetail/constants.js
  webpack/components/AnsibleHostDetail/helpers.js
  webpack/components/AnsibleRolesSwitcher/components/AnsibleRole.js
  webpack/global_index.js
Labels: Needs re-review, Needs testing

#465 Fix failing test
  webpack/components/AnsibleRolesAndVariables/__test__/AnsibleRolesAndVariablesImport.test.js
  webpack/components/AnsibleRolesAndVariables/__test__/__snapshots__/AnsibleRolesAndVariablesImport.test.js.snap
Labels: Needs testing, Waiting on contributor

#462 Fixes #33521 - Add mutation to assign ansible roles
  app/graphql/mutations/hosts/assign_ansible_roles.rb
  lib/foreman_ansible/register.rb
  test/graphql/mutations/hosts/assign_ansible_roles_mutation_test.rb
Labels: Needs testing

#467 Fixes #33602 - Do not set effective user var
  app/services/foreman_ansible/inventory_creator.rb
Labels: Needs testing
