Repository theforeman/foreman_ansible, pull requests merged in 2021-11, with the labels that each got.

#463 Fixes #33522 - Create Ansible config job
  webpack/components/AnsibleHostDetail/components/JobsTab/JobsTabHelper.js
  webpack/components/AnsibleHostDetail/components/JobsTab/NewRecurringJobHelper.js
  webpack/components/AnsibleHostDetail/components/JobsTab/NewRecurringJobModal.js
  webpack/components/AnsibleHostDetail/components/JobsTab/NewRecurringJobModal.scss
  webpack/components/AnsibleHostDetail/components/JobsTab/PreviousJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/RecurringJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
  webpack/components/AnsibleHostDetail/components/JobsTab/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/EditRoles.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/index.js
  webpack/components/AnsibleHostDetail/components/SecondaryTabRoutes.js
  webpack/components/withLoading.js
  webpack/formHelper.js
  webpack/graphql/mutations/createJobInvocation.gql
  webpack/graphql/queries/recurringJobs.gql
  webpack/testHelper.js
Labels: Needs testing

#479 Fixes #33835 - Show only one empty state for jobs
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
  webpack/components/AnsibleHostDetail/components/JobsTab/index.js
Labels: Needs testing, Not yet reviewed

#474 Fixes #33816 - fix tabs href
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
Labels: Needs testing, Not yet reviewed

#473 Fixes #33726 - Add view permissions for host detail page
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTable.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverrides.fixtures.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/index.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/JobsTab/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/index.js
  webpack/components/withLoading.js
  webpack/graphql/queries/ansibleRoles.gql
  webpack/graphql/queries/currentUserAttributes.gql
  webpack/graphql/queries/hostAnsibleRoles.gql
  webpack/graphql/queries/recurringJobs.gql
  webpack/graphql/queries/variableOverrides.gql
  webpack/permissionsHelper.js
  webpack/routes/HostgroupJobs/__test__/HostgroupJobs.fixtures.js
  webpack/routes/HostgroupJobs/__test__/HostgroupJobs.test.js
  webpack/testHelper.js
Labels: Needs testing

#484 Fixes #33854 - Handle loading and errors in inventory tab
  webpack/components/AnsibleHostDetail/components/AnsibleHostInventory/index.js
  webpack/components/ErrorState.js
  webpack/components/withLoading.js
Labels: Needs testing, Not yet reviewed

#483 Fixes #33846 - Check for permissions for roles assignment
  webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/EditRoles.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/index.js
  webpack/components/AnsibleHostDetail/components/SecondaryTabRoutes.js
  webpack/components/withLoading.js
Labels: Needs testing

#480 Fixes #33840 - Add pagination to all roles modal
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/AllRolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.fixtures.js
  webpack/graphql/queries/allAnsibleRoles.gql
  webpack/helpers/pageParamsHelper.js
Labels: Needs testing, Waiting on contributor

#478 Fixes #33831 - Cancel recurring config job
  webpack/components/AnsibleHostDetail/components/JobsTab/JobsTabHelper.js
  webpack/components/AnsibleHostDetail/components/JobsTab/NewRecurringJobHelper.js
  webpack/components/AnsibleHostDetail/components/JobsTab/RecurringJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
  webpack/graphql/mutations/cancelRecurringLogic.gql
Labels: Needs testing

#438 Fixes #33186 - New job template to run OpenSCAP scans via Ansible
  app/views/foreman_ansible/job_templates/run_openscap_scans_-_ansible_default.erb
Labels: Needs testing, Not yet reviewed

#482 Fixes #33843 - improve the convert2rhel user experience
  app/views/foreman_ansible/job_templates/convert_to_rhel.erb
Labels: Needs testing

#485 Fixes #33877 - Improve styling for roles tab
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.test.js
Labels: Needs testing

#392 Fixes #32031 - proxy batch size for Ansible
  app/models/foreman_ansible/ansible_provider.rb
  lib/foreman_ansible/register.rb
Labels: Needs testing

#476 Fixes #33827 - Check permissions when changing overrides
  app/graphql/types/overriden_ansible_variable.rb
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTable.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/EditableAction.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverrides.fixtures.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverrides.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/index.js
  webpack/graphql/queries/variableOverrides.gql
Labels: Needs testing, Not yet reviewed

#481 Fixes #33841 - Add pagination to variable overrides
  app/graphql/types/ansible_role.rb
  lib/foreman_ansible/register.rb
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesHelper.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTable.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverrides.fixtures.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverrides.test.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverridesDelete.test.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/__test__/AnsibleVariableOverridesUpdate.test.js
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/index.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
  webpack/components/AnsibleHostDetail/components/SecondaryTabRoutes.js
  webpack/graphql/queries/hostVariableOverrides.gql
  webpack/graphql/queries/variableOverrides.gql
Labels: Ready to merge

#489 Fixes #33980 - backport the RHEL OS parsing
  app/services/foreman_ansible/operating_system_parser.rb
Labels: Needs testing

#488 Fixes #33982 - Show newly added variable overrides
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/index.js
Labels: Needs testing

#486 Fixes #33883 - Handle permissions for Ansible config jobs
  foreman_ansible.gemspec
  webpack/components/AnsibleHostDetail/components/JobsTab/RecurringJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
  webpack/components/AnsibleHostDetail/components/JobsTab/index.js
  webpack/components/withLoading.js
  webpack/graphql/queries/recurringJobs.gql
  webpack/permissionsHelper.js
Labels: Needs testing
