Repository theforeman/foreman_ansible, pull requests merged in 2021-06, with the labels that each got.

#411 Fixes #32564 - Drop foreman_ansible_core
  .github/workflows/ruby_tests.yml
  app/models/foreman_ansible/ansible_provider.rb
  foreman_ansible.gemspec
  foreman_ansible_core.gemspec
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible_core.rb
  lib/foreman_ansible_core/actions.rb
  lib/foreman_ansible_core/exception.rb
  lib/foreman_ansible_core/remote_execution_core/ansible_runner.rb
  lib/foreman_ansible_core/runner/ansible_runner.rb
  lib/foreman_ansible_core/runner/command_creator.rb
  lib/foreman_ansible_core/runner/playbook.rb
  lib/foreman_ansible_core/task_launcher/ansible_runner.rb
  lib/foreman_ansible_core/task_launcher/playbook.rb
  lib/foreman_ansible_core/version.rb
  test/unit/lib/foreman_ansible_core/ansible_runner_test.rb
  test/unit/lib/foreman_ansible_core/command_creator_test.rb
  test/unit/lib/foreman_ansible_core/playbook_runner_test.rb
Labels: Needs testing

#412 Fixes #32189 - Improve ansible config report data
  app/helpers/foreman_ansible/ansible_reports_helper.rb
  app/views/foreman_ansible/config_reports/_ansible.html.erb
  test/unit/helpers/ansible_reports_helper_test.rb
Labels: Needs re-review, Needs testing

#395 Fixes #32080 - Run Ansible with flags for tags
  app/models/foreman_ansible/ansible_provider.rb
  app/views/foreman_ansible/job_templates/ansible_roles_-_ansible_default.erb
Labels: Needs testing

#406 Fixes #32399 - Add Ansible tab to host detail page
  lib/foreman_ansible/register.rb
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.scss
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.test.js
  webpack/components/AnsibleHostDetail/index.js
  webpack/global_index.js
Labels: Needs testing

#421 Fixes #32829 - align secondary tabs in host details to PF4
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
Labels: Needs testing, Not yet reviewed

#423 Refs #32399: Reference theforeman/vendor variables and not patternfly…
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.scss
Labels: Needs testing, Waiting on contributor
