Repository theforeman/foreman_ansible, pull requests merged in 2021-07, with the labels that each got.

#425 Fixes #32796 - Return the correct exit code for the rescued task
  lib/foreman_ansible_core/runner/ansible_runner.rb
Labels: Needs testing

#426 Fixes #32920 - support conversion of offline systems
  app/views/foreman_ansible/job_templates/convert_to_rhel.erb
Labels: Needs testing, Not yet reviewed

#424 Fixes #32913 - Show correct roles order for hostgroup
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  test/unit/hostgroup_ansible_role_test.rb
Labels: Needs testing, Not yet reviewed

#428 Fixes #32913 - Show correct roles order for hostgroup
  app/models/concerns/foreman_ansible/hostgroup_extensions.rb
  test/unit/hostgroup_ansible_role_test.rb
Labels: Needs testing, Not yet reviewed

#408 fixes #32494 - Removing fact parser
  .rubocop_todo.yml
  app/assets/images/foreman_ansible/Ansible.png
  app/models/foreman_ansible/fact_name.rb
  app/services/foreman_ansible/fact_importer.rb
  app/services/foreman_ansible/fact_parser.rb
  app/services/foreman_ansible/fact_sparser.rb
  app/services/foreman_ansible/operating_system_parser.rb
  app/services/foreman_ansible/structured_fact_importer.rb
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
  test/unit/services/fact_importer_test.rb
  test/unit/services/fact_parser_test.rb
  test/unit/services/fact_sparser_test.rb
  test/unit/services/structured_fact_importer_test.rb
Labels: Needs testing

#430 Fixes #33001 - Update tests for new settings registry
  test/functional/api/v2/ansible_inventories_controller_test.rb
Labels: Needs testing

#427 Fixes #32764 - Add visualization of host inventory data
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.test.js
  webpack/components/AnsibleHostDetail/components/AnsibleHostInventory/AnsibleHostInventory.js
  webpack/components/AnsibleHostDetail/components/AnsibleHostInventory/AnsibleHostInventory.scss
  webpack/components/AnsibleHostDetail/components/AnsibleHostInventory/AnsibleHostInventory.test.js
  webpack/components/AnsibleHostDetail/components/AnsibleHostInventory/index.js
  webpack/components/AnsibleRolesAndVariables/__test__/__snapshots__/AnsibleRolesAndVariablesImport.test.js.snap
Labels: Needs testing

#435 Remove ipaddress dependency
  app/models/concerns/foreman_ansible/host_managed_extensions.rb
  app/services/foreman_ansible/ansible_report_importer.rb
  foreman_ansible.gemspec
Labels: Needs testing, Waiting on contributor

#433 Fixes #33142 - Add missing template for variable overrides
  app/views/api/v2/ansible_override_values/index.json.rabl
  app/views/api/v2/ansible_variables/show.json.rabl
Labels: Needs re-review, Needs testing
