Repository theforeman/foreman_ansible, pull requests merged in 2022-02, with the labels that each got.

#496 Fixes #34242 - Add a Job-Template to trigger Windows Updates via Ansible
  app/views/foreman_ansible/job_templates/ansible_windows_updates.erb
Labels: Needs testing, Waiting on contributor

#510 Host Ansible jobs - Readable cron line
  webpack/components/AnsibleHostDetail/components/JobsTab/JobsTabHelper.js
  webpack/components/AnsibleHostDetail/components/JobsTab/PreviousJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/RecurringJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.test.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTabHelper.test.js
  webpack/routes/HostgroupJobs/__test__/HostgroupJobs.test.js
Labels: Needs testing, Waiting on contributor

#506 Fixes #34318 - Parse playbooks from proxy to job templates
  app/services/foreman_ansible/playbooks_importer.rb
  test/fixtures/playbooks_example_output.json
  test/fixtures/sample_playbooks.json
  test/unit/import_playbooks_test.rb
Labels: Needs testing

#511 Fixes #34458 - Show Hostgroup jobs on the Host Detail page
  webpack/components/AnsibleHostDetail/components/JobsTab/JobsTabHelper.js
  webpack/components/AnsibleHostDetail/components/JobsTab/PreviousJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/RecurringJobsTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/__test__/JobsTab.fixtures.js
  webpack/components/AnsibleHostDetail/components/JobsTab/index.js
  webpack/components/AnsibleHostDetail/components/SecondaryTabRoutes.js
  webpack/graphql/queries/recurringJobs.gql
Labels: Needs testing

#514 Fixes #34512 - coerce batch size to integer (#512)
  app/models/foreman_ansible/ansible_provider.rb
  test/unit/ansible_provider_test.rb
Labels: Needs testing, Not yet reviewed
