Repository theforeman/foreman_ansible, pull requests merged in 2022-01, with the labels that each got.

#493 Fixes #34150 - align secondary tabs in host page
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.js
  webpack/components/AnsibleHostDetail/AnsibleHostDetail.scss
Labels: Needs testing

#497 Fixes #34253 - Tags input is expected as a string
  app/models/foreman_ansible/ansible_provider.rb
Labels: Needs testing, Waiting on contributor

#495 Fixes #34190 - consume pagination from core
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/PreviousJobsTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/AllRolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTable.js
  webpack/components/AnsibleRolesAndVariables/AnsibleRolesAndVariables.js
  webpack/components/AnsibleRolesSwitcher/components/AvailableRolesList.js
  webpack/components/AnsibleRolesSwitcher/components/__snapshots__/AvailableRolesList.test.js.snap
  webpack/components/withPagination.js
  webpack/helpers/pageParamsHelper.js
  webpack/helpers/paginationHelper.js
Labels: Needs testing

#500 Test Host Detail page as default
  test/functional/hosts_controller_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#499 Fixes #34272 - improve modals UI in host page
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/EditRoles.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.test.js
  webpack/components/DualList/index.js
Labels: Needs testing

#501 Fixes #34272 - fix modals UI in host page
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/index.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/EditRoles.test.js
  webpack/components/AnsibleHostDetail/components/RolesTab/__test__/RolesTab.test.js
  webpack/components/DualList/index.js
Labels: Needs testing

#502 Fixes #34283 - customize variables EmptyState message
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/index.js
Labels: Needs testing

#503 Fixes #34286 - add bottom pagination in all new host page tables
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTable.js
  webpack/components/AnsibleHostDetail/components/JobsTab/PreviousJobsTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/AllRolesTable.js
  webpack/components/AnsibleHostDetail/components/RolesTab/RolesTable.js
Labels: Needs testing

#504 Add variables column on Ansible roles page
  app/views/ansible_roles/index.html.erb
Labels: Needs testing

#508 Fixes #34334 - Import roles - Fix pagination
  webpack/components/AnsibleRolesAndVariables/AnsibleRolesAndVariables.js
Labels: Needs testing

#505 Fixes #34313 - Import roles - disable Submit button
  webpack/components/AnsibleRolesAndVariables/AnsibleRolesAndVariables.js
  webpack/components/AnsibleRolesAndVariables/AnsibleRolesAndVariablesActions.js
  webpack/components/AnsibleRolesAndVariables/AnsibleRolesAndVariablesConstants.js
  webpack/components/AnsibleRolesAndVariables/AnsibleRolesAndVariablesSelectors.js
  webpack/components/AnsibleRolesAndVariables/index.js
Labels: Needs testing
