Repository theforeman/foreman_ansible, pull requests merged in 2022-05, with the labels that each got.

#530 Extract strings for Foreman 3.3 translation
  locale/action_names.rb
  locale/ca/foreman_ansible.po
  locale/cs_CZ/foreman_ansible.po
  locale/de/foreman_ansible.po
  locale/en/foreman_ansible.po
  locale/en_GB/foreman_ansible.po
  locale/es/foreman_ansible.po
  locale/foreman_ansible.pot
  locale/fr/foreman_ansible.po
  locale/gl/foreman_ansible.po
  locale/it/foreman_ansible.po
  locale/ja/foreman_ansible.po
  locale/ko/foreman_ansible.po
  locale/nl_NL/foreman_ansible.po
  locale/pl/foreman_ansible.po
  locale/pt_BR/foreman_ansible.po
  locale/ru/foreman_ansible.po
  locale/sv_SE/foreman_ansible.po
  locale/zh_CN/foreman_ansible.po
  locale/zh_TW/foreman_ansible.po
Labels: Needs testing

#532 Fixes #34886 - Github actions - remove NodeJS 10 and add NodeJS 14
  .github/workflows/js_tests.yml
Labels: Needs testing, Waiting on contributor

#529 Fixes #34796 - Fixes for Rails 6.1 upgrade
  app/helpers/foreman_ansible/hosts_helper.rb
  app/helpers/foreman_ansible/hosts_helper_extensions.rb
  app/services/foreman_ansible/variables_importer.rb
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
Labels: Needs testing

#533 Fixes #34911 - prevent reset to initial roles values in EditRolesForm
  webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/EditRolesForm.js
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#534 Fixes #34912 - enable to edit roles when all are assigned
  webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/index.js
  webpack/components/withLoading.js
Labels: Needs testing

#536 Bump foreman_ansible version to 8.0.0
  lib/foreman_ansible/version.rb
Labels: Needs testing, Waiting on contributor
