Repository theforeman/foreman_ansible, pull requests merged in 2023-02, with the labels that each got.

#587 Fixes #35994 - check if user has administrator permissions by its usergroup
  webpack/graphql/queries/currentUserAttributes.gql
  webpack/permissionsHelper.js
  webpack/testHelper.js
Labels: Waiting on contributor

#592 Fixes #36021 - add an option to configure Ansible job for hostgroup
  app/helpers/foreman_ansible/ansible_hostgroups_helper.rb
Labels: Waiting on contributor

#596 Bump version 11.1.0
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor

#595 update links in readme to use HTTPS and point at general support page
  README.md
Labels: Not yet reviewed, Waiting on contributor

#594 link to the current inventory code
  README.md
Labels: Not yet reviewed, Waiting on contributor

#599 open up @theforeman dependencies
  package.json
Labels: Not yet reviewed, Waiting on contributor

#600 Fixes #36136 - make sure validatorRule is a string
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTableHelper.js
Labels: Not yet reviewed

#601 Fixes #36136 - make sure validatorRule is a string
  foreman_ansible.gemspec
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTableHelper.js
Labels: Waiting on contributor

#602 Fixes #36136 - make sure validatorRule is a string
  foreman_ansible.gemspec
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/AnsibleVariableOverridesTableHelper.js
Labels: Waiting on contributor

#603 Bump version to 7.1.5
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor

#606 Fix CI issues in the 10.0-stable branch
  .github/workflows/js_tests.yml
  .github/workflows/ruby_tests.yml
  foreman_ansible.gemspec
  package.json
Labels: Not yet reviewed, Waiting on contributor

#604 Bump version 10.4.1
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor

#590 Fixes #36011 - Split Capsule and Smart Proxy upgrades to separate tem…
  app/helpers/foreman_ansible/smart_proxies_helper.rb
  app/views/foreman_ansible/job_templates/capsule_upgrade_-_ansible_default.erb
  app/views/foreman_ansible/job_templates/smart_proxy_upgrade_-_ansible_default.erb
Labels: Waiting on contributor
