Repository theforeman/foreman_ansible, pull requests merged in 2023-09, with the labels that each got.

#664 allow foreman_remote_execution 11
  foreman_ansible.gemspec
Labels: Not yet reviewed, Waiting on contributor

#665 Bump version to 12.0.7
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor

#564 Fixes #35579 - Pass parameters as keyword arguments
  test/functional/api/v2/ansible_inventories_controller_test.rb
Labels: Not yet reviewed

#651 i18n - pulling from tx
  app/assets/javascripts/foreman_ansible/locale/ca/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/cs_CZ/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/de/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/en/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/en_GB/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/es/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/fr/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/gl/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/it/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ja/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ka/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ko/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/nl_NL/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/pl/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/pt_BR/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ru/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/sv_SE/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/zh_CN/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/zh_TW/foreman_ansible.js
  locale/action_names.rb
  locale/ca/LC_MESSAGES/foreman_ansible.mo
  locale/ca/foreman_ansible.po
  locale/cs_CZ/LC_MESSAGES/foreman_ansible.mo
  locale/cs_CZ/foreman_ansible.po
  locale/de/LC_MESSAGES/foreman_ansible.mo
  locale/de/foreman_ansible.po
  locale/en/LC_MESSAGES/foreman_ansible.mo
  locale/en/foreman_ansible.po
  locale/en_GB/LC_MESSAGES/foreman_ansible.mo
  locale/en_GB/foreman_ansible.po
  locale/es/LC_MESSAGES/foreman_ansible.mo
  locale/es/foreman_ansible.po
  locale/foreman_ansible.pot
  locale/fr/LC_MESSAGES/foreman_ansible.mo
  locale/fr/foreman_ansible.po
  locale/gl/LC_MESSAGES/foreman_ansible.mo
  locale/gl/foreman_ansible.po
  locale/it/LC_MESSAGES/foreman_ansible.mo
  locale/it/foreman_ansible.po
  locale/ja/LC_MESSAGES/foreman_ansible.mo
  locale/ja/foreman_ansible.po
  locale/ka/LC_MESSAGES/foreman_ansible.mo
  locale/ka/foreman_ansible.po
  locale/ko/LC_MESSAGES/foreman_ansible.mo
  locale/ko/foreman_ansible.po
  locale/nl_NL/LC_MESSAGES/foreman_ansible.mo
  locale/nl_NL/foreman_ansible.po
  locale/pl/LC_MESSAGES/foreman_ansible.mo
  locale/pl/foreman_ansible.po
  locale/pt_BR/LC_MESSAGES/foreman_ansible.mo
  locale/pt_BR/foreman_ansible.po
  locale/ru/LC_MESSAGES/foreman_ansible.mo
  locale/ru/foreman_ansible.po
  locale/sv_SE/LC_MESSAGES/foreman_ansible.mo
  locale/sv_SE/foreman_ansible.po
  locale/zh_CN/LC_MESSAGES/foreman_ansible.mo
  locale/zh_CN/foreman_ansible.po
  locale/zh_TW/LC_MESSAGES/foreman_ansible.mo
  locale/zh_TW/foreman_ansible.po
Labels: Waiting on contributor
