Repository theforeman/foreman_ansible, pull requests merged in 2023-01, with the labels that each got.

#584 Bump version 10.2.0
  lib/foreman_ansible/version.rb
Labels: Waiting on contributor

#580 Fixes #35883 - don't fail if data is missing due to no_log
  app/helpers/foreman_ansible/ansible_reports_helper.rb
  test/unit/helpers/ansible_reports_helper_test.rb
Labels: Not yet reviewed

#583 Fixes #35885 - Error printing report with multiple results
  app/helpers/foreman_ansible/ansible_reports_helper.rb
  test/fixtures/report.json
  test/unit/concerns/config_reports_extensions_test.rb
  test/unit/helpers/ansible_reports_helper_test.rb
Labels: Not yet reviewed

#589 Fixes #36004 - Migration error 'column settings.category does not exist'
  db/migrate/20210818083407_fix_ansible_setting_category_to_dsl.rb
Labels: Not yet reviewed, Waiting on contributor
