Repository theforeman/foreman_ansible, pull requests merged in 2024-09, with the labels that each got.

#732 Make theforeman-rubocop dev dep
  Gemfile
  foreman_ansible.gemspec
Labels: Waiting on contributor

#731 i18n - pulling from tx
  app/assets/javascripts/foreman_ansible/locale/ca/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/cs_CZ/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/de/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/en/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/en_GB/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/es/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/fr/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/gl/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/it/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ja/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ka/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ko/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/nl_NL/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/pl/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/pt_BR/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ru/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/sv_SE/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/zh_CN/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/zh_TW/foreman_ansible.js
  locale/ca/foreman_ansible.po
  locale/cs_CZ/LC_MESSAGES/foreman_ansible.mo
  locale/cs_CZ/foreman_ansible.po
  locale/de/LC_MESSAGES/foreman_ansible.mo
  locale/de/foreman_ansible.po
  locale/en/foreman_ansible.po
  locale/en_GB/LC_MESSAGES/foreman_ansible.mo
  locale/en_GB/foreman_ansible.po
  locale/es/LC_MESSAGES/foreman_ansible.mo
  locale/es/foreman_ansible.po
  locale/foreman_ansible.pot
  locale/fr/LC_MESSAGES/foreman_ansible.mo
  locale/fr/foreman_ansible.po
  locale/gl/foreman_ansible.po
  locale/it/LC_MESSAGES/foreman_ansible.mo
  locale/it/foreman_ansible.po
  locale/ja/LC_MESSAGES/foreman_ansible.mo
  locale/ja/foreman_ansible.po
  locale/ka/LC_MESSAGES/foreman_ansible.mo
  locale/ka/foreman_ansible.po
  locale/ko/LC_MESSAGES/foreman_ansible.mo
  locale/ko/foreman_ansible.po
  locale/nl_NL/foreman_ansible.po
  locale/pl/foreman_ansible.po
  locale/pt_BR/LC_MESSAGES/foreman_ansible.mo
  locale/pt_BR/foreman_ansible.po
  locale/ru/LC_MESSAGES/foreman_ansible.mo
  locale/ru/foreman_ansible.po
  locale/sv_SE/foreman_ansible.po
  locale/zh_CN/LC_MESSAGES/foreman_ansible.mo
  locale/zh_CN/foreman_ansible.po
  locale/zh_TW/LC_MESSAGES/foreman_ansible.mo
  locale/zh_TW/foreman_ansible.po
Labels: Waiting on contributor

#733 Ignore locale/action_names.rb
  .gitignore
  locale/action_names.rb
Labels: Waiting on contributor

#736 Bump version to 14.2.2
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor

#718 Fixes #37451 - Support Zeitwerk loader
  app/controllers/ansible_roles_controller.rb
  app/controllers/ansible_variables_controller.rb
  app/controllers/api/v2/ansible_roles_controller.rb
  app/controllers/ui_ansible_roles_controller.rb
  app/jobs/import_playbooks_job/async/sync_playbooks.rb
  app/jobs/sync_roles_and_variables.rb
  app/services/foreman_ansible/api_roles_importer.rb
  app/services/foreman_ansible/ui_roles_importer.rb
  foreman_ansible.gemspec
  lib/foreman_ansible/engine.rb
  lib/foreman_ansible/register.rb
  test/functional/ansible_variables_controller_test.rb
  test/functional/ui_ansible_roles_controller_test.rb
  test/unit/services/ui_roles_importer_test.rb
Labels: Needs re-review

#738 Bump version to 15.0.0
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor

#730 Make Ansible Playbook more readable and apply best practices
  app/views/foreman_ansible/job_templates/download_and_execute_script.erb
Labels: Waiting on contributor

#740 Bump version to 15.0.1
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor
