Repository theforeman/foreman_ansible, pull requests merged in 2024-03, with the labels that each got.

#694 Release gem GH action
  .github/workflows/release_gem.yml
Labels: Waiting on contributor

#697 Allow the 13.y.z line of rex
  foreman_ansible.gemspec
Labels: Waiting on contributor

#701 use shared GHA workflow for JS tests
  .github/workflows/js_tests.yml
Labels: Waiting on contributor

#702 Send resource as keyword argument in resource_name
  app/controllers/ui_ansible_roles_controller.rb
  lib/foreman_ansible/register.rb
Labels: Not yet reviewed, Waiting on contributor

#684 Fixes #37091 - Pretty print long YAML list
  app/views/foreman_ansible/job_templates/package_action_-_ansible_default.erb
Labels: Not yet reviewed

#703 Bump version to 14.0.0
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor
