Repository theforeman/foreman_ansible, pull requests merged in 2025-03, with the labels that each got.

#756 Fixes #38250 - keep newlines and trailing spaces in Ansible variables
  webpack/components/AnsibleHostDetail/components/AnsibleVariableOverrides/EditableValue.js
Labels: Not yet reviewed, Stable branch

#757 Bump version to 15.0.6
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor, Stable branch

#758 update acts_as_list requirement
  foreman_ansible.gemspec
Labels: Waiting on contributor

#760 Loosen dependency on REX to allow <17
  foreman_ansible.gemspec
Labels: Not yet reviewed, Waiting on contributor

#761 Bump version to 16.0.0
  foreman_ansible.gemspec
  lib/foreman_ansible/register.rb
  lib/foreman_ansible/version.rb
Labels: Waiting on contributor

#762 i18n - pulling from tx
  app/assets/javascripts/foreman_ansible/locale/fr/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ja/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/ko/foreman_ansible.js
  app/assets/javascripts/foreman_ansible/locale/zh_CN/foreman_ansible.js
  locale/en/LC_MESSAGES/foreman_ansible.mo
  locale/en_GB/LC_MESSAGES/foreman_ansible.mo
  locale/foreman_ansible.pot
  locale/fr/LC_MESSAGES/foreman_ansible.mo
  locale/fr/foreman_ansible.po
  locale/ja/LC_MESSAGES/foreman_ansible.mo
  locale/ja/foreman_ansible.po
  locale/ko/LC_MESSAGES/foreman_ansible.mo
  locale/ko/foreman_ansible.po
  locale/zh_CN/LC_MESSAGES/foreman_ansible.mo
  locale/zh_CN/foreman_ansible.po
Labels: Waiting on contributor, Stable branch

#763 Bump version to 15.0.7
  lib/foreman_ansible/version.rb
Labels: Not yet reviewed, Waiting on contributor, Stable branch
